version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ./cert.pem:/api-test/cert.pem
      - ./key.pem:/api-test/key.pem
